### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by yzhang-gh** [apm1467/zhihu-heartbeat#3]
几个小建议

1. [pangu.js](https://github.com/vinta/pangu.js) 强迫症福音
2. 引用的想法用卡片样式（边框和阴影），和知乎网页版更像
3. 滚动条
4. 头像和用户名（可以更像网页版）

貌似 1 和 3 在 Mac 上都不是问题😓

Suggestion|Now
---|---
![affter](https://user-images.githubusercontent.com/7588612/55674631-ff29e400-58ae-11e9-91c4-03e48536a51b.png) | ![Now](https://user-images.githubusercontent.com/7588612/55674885-744ae880-58b2-11e9-8a5e-fc93ff875c35.png)

---

之前以为这个项目已经不维护了，就没有 fork 自己下载了源码改了一下，现在估计 conflict 得很严重了。。。

<details>
<summary>可能有用的代码</summary>

### For point 2

```css
.images, .video {
    line-height: 0;
    margin-top: .75rem;
    width: 100%;
    text-align: center;
    border-radius: 4px;
    overflow: hidden;
}

.single-img, .video .thumbnail {
    max-width: 100%;
    max-height: 250px;
    border-radius: 4px;
}

.origin-pin {
    font-size: 16px;
    margin: .2rem;
    margin-top: 1rem;
    padding: 1rem;
    border: 1px solid #464646;
    border-radius: 4px;
    box-shadow: 2px 2px 4px rgba(80, 80, 80, 0.25);
}
```

</details>
